spring:
  application:
    name: msvc-authms
  datasource:
    url: jdbc:sqlserver://upiita-pt.database.windows.net:1433;database=microserviciosPT;user=upiita@upiita-pt;password=Ipn2024!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: upiita
    password: 'Ipn2024!'
#    url: jdbc:sqlserver://192.168.3.3:1433;databaseName=ptdb;encrypt=false;trustServerCertificate=true;
#    username: sa
#    password: '040201' 
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.SQLServerDialec
      show_sql: true
      properties:
        hibernate.format_sql: true
logging:
  level:
    com.zaxxer.hikari: DEBUG
  mail:
    host: smtp.gmail.com
    port: 587
    username: diegoflowers444@gmail.com
    password: zxcj nnsx dvyp xoff
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081
jwt:
  secret: 357638792F423F4421472B4B6250655368566D597133743677397A2443264629
eureka:
  instance:
    ip-address: 158.23.81.1 #158.23.81.1
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://158.23.81.1:8761/eureka #http://158.23.81.1:8761/eureka
#logging:
#  level:
#    org.hibernate: DEBUG
#    com.zaxxer.hikari: DEBUG