spring:
  application:
    name: msvc-authms
  datasource:
    url: jdbc:sqlserver://158.23.246.23:1433;database=microserviciosPT;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sa
    password: 'Ipn2024!'
#    url: jdbc:sqlserver://192.168.3.3:1433;databaseName=ptdb;encrypt=false;trustServerCertificate=true;
#    username: sa
#    password: '040201' 
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      dialect: org.hibernate.dialect.SQLServerDialec
  mail:
    host: smtp.gmail.com
    port: 587
    username: diegoflowers444@gmail.com
    password: zxcj nnsx dvyp xoff
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081
jwt:
  secret: 357638792F423F4421472B4B6250655368566D597133743677397A2443264629
eureka:
  instance:
    ip-address: 158.23.246.23 #158.23.246.23
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://158.23.246.23:8761/eureka #http://158.23.246.23:8761/eureka
